// Datos de habitaciones — fuente: FICHA TECNICA HABITACIONES.xlsx
// 'Standard de Lujo' fue reunificado con 'Ejecutiva en Suite' (no es una categoria real, ver nota de Gerencia).
const ROOMS = [
  {
    "numero": 102,
    "piso": 1,
    "pasillo": "PORCELANATO",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": "HANDICAP",
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "SI",
    "aire_ac": "SI",
    "vista": "CERRO"
  },
  {
    "numero": 103,
    "piso": 1,
    "pasillo": "PORCELANATO",
    "bloque": "APART",
    "categoria": "DEPARTAMENTO",
    "piso_material": "MADERA",
    "cama": "QUEEN",
    "cant_camas": 1,
    "max_personas": 3,
    "condicion_esp": "SOFA CAMA",
    "observ": "KICHENETTE",
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "SI",
    "aire_ac": "SI",
    "vista": "CERRO"
  },
  {
    "numero": 104,
    "piso": 1,
    "pasillo": "PORCELANATO",
    "bloque": "APART",
    "categoria": "DEPARTAMENTO",
    "piso_material": "MADERA",
    "cama": "QUEEN",
    "cant_camas": 1,
    "max_personas": 3,
    "condicion_esp": "SOFA CAMA",
    "observ": "KICHENETTE",
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "SI",
    "aire_ac": "SI",
    "vista": "CERRO"
  },
  {
    "numero": 105,
    "piso": 1,
    "pasillo": "PORCELANATO",
    "bloque": "APART",
    "categoria": "DEPARTAMENTO",
    "piso_material": "MADERA",
    "cama": "QUEEN",
    "cant_camas": 1,
    "max_personas": 3,
    "condicion_esp": "SOFA CAMA",
    "observ": "KICHENETTE",
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "SI",
    "vista": "CERRO"
  },
  {
    "numero": 106,
    "piso": 1,
    "pasillo": "PORCELANATO",
    "bloque": "APART",
    "categoria": "DEPARTAMENTO",
    "piso_material": "MADERA",
    "cama": "QUEEN",
    "cant_camas": 1,
    "max_personas": 3,
    "condicion_esp": "SOFA CAMA",
    "observ": "KICHENETTE",
    "falta_pintar": false,
    "medida_m2": 38,
    "balcon": "NO",
    "aire_ac": "SI",
    "vista": "CERRO"
  },
  {
    "numero": 108,
    "piso": 1,
    "pasillo": "PORCELANATO",
    "bloque": "APART",
    "categoria": "DEPARTAMENTO",
    "piso_material": "MADERA",
    "cama": "QUEEN",
    "cant_camas": 1,
    "max_personas": 3,
    "condicion_esp": "SOFA CAMA",
    "observ": "KICHENETTE",
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "GRANDE",
    "aire_ac": "SI",
    "vista": "MAR"
  },
  {
    "numero": 109,
    "piso": 1,
    "pasillo": "PORCELANATO",
    "bloque": "APART",
    "categoria": "DEPARTAMENTO",
    "piso_material": "MADERA",
    "cama": "QUEEN",
    "cant_camas": 1,
    "max_personas": 3,
    "condicion_esp": "SOFA CAMA",
    "observ": "KICHENETTE",
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "GRANDE",
    "aire_ac": "SI",
    "vista": "MAR"
  },
  {
    "numero": 201,
    "piso": 2,
    "pasillo": "ALFOMBRA",
    "bloque": "ECONO",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "CERRO"
  },
  {
    "numero": 202,
    "piso": 2,
    "pasillo": "ALFOMBRA",
    "bloque": "ECONO",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "CERRO"
  },
  {
    "numero": 203,
    "piso": 2,
    "pasillo": "ALFOMBRA",
    "bloque": "ECONO",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "CERRO"
  },
  {
    "numero": 204,
    "piso": 2,
    "pasillo": "ALFOMBRA",
    "bloque": "ECONO",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "CERRO"
  },
  {
    "numero": 205,
    "piso": 2,
    "pasillo": "ALFOMBRA",
    "bloque": "ECONO",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "CERRO"
  },
  {
    "numero": 206,
    "piso": 2,
    "pasillo": "ALFOMBRA",
    "bloque": "ECONO",
    "categoria": "CUADRUPLE EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 4,
    "max_personas": 4,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 38,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 207,
    "piso": 2,
    "pasillo": "ALFOMBRA",
    "bloque": "ECONO",
    "categoria": "CUADRUPLE EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 4,
    "max_personas": 4,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 38,
    "balcon": "NO",
    "aire_ac": "SI",
    "vista": "MAR"
  },
  {
    "numero": 208,
    "piso": 2,
    "pasillo": "ALFOMBRA",
    "bloque": "ECONO",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "SI",
    "vista": "MAR"
  },
  {
    "numero": 209,
    "piso": 2,
    "pasillo": "ALFOMBRA",
    "bloque": "ECONO",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "SI",
    "vista": "MAR"
  },
  {
    "numero": 210,
    "piso": 2,
    "pasillo": "ALFOMBRA",
    "bloque": "ECONO",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 211,
    "piso": 2,
    "pasillo": "ALFOMBRA",
    "bloque": "ECONO",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 212,
    "piso": 2,
    "pasillo": "ALFOMBRA",
    "bloque": "ECONO",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 301,
    "piso": 3,
    "pasillo": "PORCELANATO",
    "bloque": "ECONO",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": "PET FRIENDLY",
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "CERRO"
  },
  {
    "numero": 302,
    "piso": 3,
    "pasillo": "PORCELANATO",
    "bloque": "ECONO",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "CERRO"
  },
  {
    "numero": 303,
    "piso": 3,
    "pasillo": "PORCELANATO",
    "bloque": "ECONO",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "CERRO"
  },
  {
    "numero": 304,
    "piso": 3,
    "pasillo": "PORCELANATO",
    "bloque": "ECONO",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "CERRO"
  },
  {
    "numero": 305,
    "piso": 3,
    "pasillo": "PORCELANATO",
    "bloque": "ECONO",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "CERRO"
  },
  {
    "numero": 306,
    "piso": 3,
    "pasillo": "PORCELANATO",
    "bloque": "ECONO",
    "categoria": "CUADRUPLE EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 4,
    "max_personas": 4,
    "condicion_esp": "4 CAMAS",
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 38,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 307,
    "piso": 3,
    "pasillo": "PORCELANATO",
    "bloque": "ECONO",
    "categoria": "CUADRUPLE EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 4,
    "max_personas": 4,
    "condicion_esp": "4 CAMAS",
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 38,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 308,
    "piso": 3,
    "pasillo": "PORCELANATO",
    "bloque": "ECONO",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 309,
    "piso": 3,
    "pasillo": "PORCELANATO",
    "bloque": "ECONO",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 310,
    "piso": 3,
    "pasillo": "PORCELANATO",
    "bloque": "ECONO",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 311,
    "piso": 3,
    "pasillo": "PORCELANATO",
    "bloque": "ECONO",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "ALFOMBRA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": "PERSIANA BLACKOUT Y MAMPARA",
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 312,
    "piso": 3,
    "pasillo": "PORCELANATO",
    "bloque": "ECONO",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": "PET FRIENDLY",
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 401,
    "piso": 4,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "CERRO"
  },
  {
    "numero": 402,
    "piso": 4,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "CERRO"
  },
  {
    "numero": 403,
    "piso": 4,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "CERRO"
  },
  {
    "numero": 404,
    "piso": 4,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "CERRO"
  },
  {
    "numero": 405,
    "piso": 4,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": true,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "CERRO"
  },
  {
    "numero": 406,
    "piso": 4,
    "pasillo": "ALFOMBRA",
    "bloque": "PREMIUM",
    "categoria": "JUNIOR EN SUITE",
    "piso_material": "MADERA",
    "cama": "QUEEN",
    "cant_camas": 1,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 38,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 407,
    "piso": 4,
    "pasillo": "ALFOMBRA",
    "bloque": "PREMIUM",
    "categoria": "JUNIOR EN SUITE",
    "piso_material": "MADERA",
    "cama": "QUEEN",
    "cant_camas": 1,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 38,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 408,
    "piso": 4,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 409,
    "piso": 4,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 410,
    "piso": 4,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 411,
    "piso": 4,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 412,
    "piso": 4,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 501,
    "piso": 5,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "CERRO"
  },
  {
    "numero": 502,
    "piso": 5,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": "COMUNICADA",
    "observ": "COMUNICA CON 503",
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "CERRO"
  },
  {
    "numero": 503,
    "piso": 5,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "QUEEN",
    "cant_camas": 1,
    "max_personas": 2,
    "condicion_esp": "COMUNICADA",
    "observ": "COMUNICA CON 502",
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "CERRO"
  },
  {
    "numero": 504,
    "piso": 5,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": "COMUNICADA",
    "observ": "COMUNICA CON 505",
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "CERRO"
  },
  {
    "numero": 505,
    "piso": 5,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "QUEEN",
    "cant_camas": 1,
    "max_personas": 2,
    "condicion_esp": "COMUNICADA",
    "observ": "COMUNICA CON 504",
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "CERRO"
  },
  {
    "numero": 506,
    "piso": 5,
    "pasillo": "ALFOMBRA",
    "bloque": "PREMIUM",
    "categoria": "JUNIOR EN SUITE",
    "piso_material": "MADERA",
    "cama": "QUEEN",
    "cant_camas": 1,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 38,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 507,
    "piso": 5,
    "pasillo": "ALFOMBRA",
    "bloque": "PREMIUM",
    "categoria": "JUNIOR EN SUITE",
    "piso_material": "MADERA",
    "cama": "QUEEN",
    "cant_camas": 1,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 38,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 508,
    "piso": 5,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "QUEEN",
    "cant_camas": 1,
    "max_personas": 2,
    "condicion_esp": "COMUNICADA",
    "observ": "COMUNICA CON 509",
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 509,
    "piso": 5,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": "COMUNICADA",
    "observ": "COMUNICA CON 508",
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 510,
    "piso": 5,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "QUEEN",
    "cant_camas": 1,
    "max_personas": 2,
    "condicion_esp": "COMUNICADA",
    "observ": "COMUNICA CON 511",
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 511,
    "piso": 5,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": "COMUNICADA",
    "observ": "COMUNICA CON 510",
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 512,
    "piso": 5,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 601,
    "piso": 6,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "CERRO"
  },
  {
    "numero": 602,
    "piso": 6,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": "COMUNICADA",
    "observ": "COMUNICA CON 603",
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "CERRO"
  },
  {
    "numero": 603,
    "piso": 6,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "QUEEN",
    "cant_camas": 1,
    "max_personas": 2,
    "condicion_esp": "COMUNICADA",
    "observ": "COMUNICA CON 602",
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "CERRO"
  },
  {
    "numero": 604,
    "piso": 6,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": "COMUNICADA",
    "observ": "COMUNICA CON 605",
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "CERRO"
  },
  {
    "numero": 605,
    "piso": 6,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "QUEEN",
    "cant_camas": 1,
    "max_personas": 2,
    "condicion_esp": "COMUNICADA",
    "observ": "COMUNICA CON 604",
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "CERRO"
  },
  {
    "numero": 606,
    "piso": 6,
    "pasillo": "ALFOMBRA",
    "bloque": "PREMIUM",
    "categoria": "JUNIOR EN SUITE",
    "piso_material": "MADERA",
    "cama": "QUEEN",
    "cant_camas": 1,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 38,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 607,
    "piso": 6,
    "pasillo": "ALFOMBRA",
    "bloque": "PREMIUM",
    "categoria": "JUNIOR EN SUITE",
    "piso_material": "MADERA",
    "cama": "QUEEN",
    "cant_camas": 1,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 38,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 608,
    "piso": 6,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "QUEEN",
    "cant_camas": 1,
    "max_personas": 2,
    "condicion_esp": "COMUNICADA",
    "observ": "COMUNICA CON 609",
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 609,
    "piso": 6,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": "COMUNICADA",
    "observ": "COMUNICA CON 608",
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 610,
    "piso": 6,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "QUEEN",
    "cant_camas": 1,
    "max_personas": 2,
    "condicion_esp": "COMUNICADA",
    "observ": "COMUNICA CON 611",
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 611,
    "piso": 6,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 3,
    "max_personas": 3,
    "condicion_esp": "COMUNICADA",
    "observ": "COMUNICA CON 610",
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 612,
    "piso": 6,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 701,
    "piso": 7,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": true,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "CERRO"
  },
  {
    "numero": 702,
    "piso": 7,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": "COMUNICADA",
    "observ": "COMUNICA CON 703",
    "falta_pintar": true,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "CERRO"
  },
  {
    "numero": 703,
    "piso": 7,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "QUEEN",
    "cant_camas": 1,
    "max_personas": 2,
    "condicion_esp": "COMUNICADA",
    "observ": "COMUNICA CON 702",
    "falta_pintar": true,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "CERRO"
  },
  {
    "numero": 704,
    "piso": 7,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": "COMUNICADA",
    "observ": "COMUNICA CON 705",
    "falta_pintar": true,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "CERRO"
  },
  {
    "numero": 705,
    "piso": 7,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "QUEEN",
    "cant_camas": 1,
    "max_personas": 2,
    "condicion_esp": "COMUNICADA",
    "observ": "COMUNICA CON 704",
    "falta_pintar": true,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "CERRO"
  },
  {
    "numero": 706,
    "piso": 7,
    "pasillo": "ALFOMBRA",
    "bloque": "PREMIUM",
    "categoria": "JUNIOR EN SUITE",
    "piso_material": "MADERA",
    "cama": "QUEEN",
    "cant_camas": 1,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 38,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 707,
    "piso": 7,
    "pasillo": "ALFOMBRA",
    "bloque": "PREMIUM",
    "categoria": "JUNIOR EN SUITE",
    "piso_material": "MADERA",
    "cama": "QUEEN",
    "cant_camas": 1,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 38,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 708,
    "piso": 7,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "QUEEN",
    "cant_camas": 1,
    "max_personas": 2,
    "condicion_esp": "COMUNICADA",
    "observ": "COMUNICA CON 709",
    "falta_pintar": true,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 709,
    "piso": 7,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": "COMUNICADA",
    "observ": "COMUNICA CON 708",
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 710,
    "piso": 7,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "QUEEN",
    "cant_camas": 1,
    "max_personas": 2,
    "condicion_esp": "COMUNICADA",
    "observ": "COMUNICA CON 711",
    "falta_pintar": true,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 711,
    "piso": 7,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 3,
    "max_personas": 3,
    "condicion_esp": "COMUNICADA",
    "observ": "COMUNICA CON 710",
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 712,
    "piso": 7,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "TWIN XL",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "NO",
    "vista": "MAR"
  },
  {
    "numero": 801,
    "piso": 8,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "FULL 2 PLAZAS",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "SI",
    "vista": "CERRO"
  },
  {
    "numero": 802,
    "piso": 8,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "FULL 2 PLAZAS",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "SI",
    "vista": "CERRO"
  },
  {
    "numero": 803,
    "piso": 8,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "FULL 2 PLAZAS",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "SI",
    "vista": "CERRO"
  },
  {
    "numero": 804,
    "piso": 8,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "FULL 2 PLAZAS",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "SI",
    "vista": "CERRO"
  },
  {
    "numero": 805,
    "piso": 8,
    "pasillo": "ALFOMBRA",
    "bloque": "PREMIUM",
    "categoria": "SUITE PRESIDENCIAL",
    "piso_material": "MADERA",
    "cama": "KING SIZE",
    "cant_camas": 1,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 85,
    "balcon": "NO",
    "aire_ac": "SI",
    "vista": "MAR"
  },
  {
    "numero": 806,
    "piso": 8,
    "pasillo": "ALFOMBRA",
    "bloque": "PREMIUM",
    "categoria": "SUITE PRESIDENCIAL",
    "piso_material": "MADERA",
    "cama": "KING SIZE",
    "cant_camas": 1,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 85,
    "balcon": "NO",
    "aire_ac": "SI",
    "vista": "MAR"
  },
  {
    "numero": 807,
    "piso": 8,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "FULL 2 PLAZAS",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "SI",
    "vista": "MAR"
  },
  {
    "numero": 808,
    "piso": 8,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "FULL 2 PLAZAS",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "SI",
    "vista": "MAR"
  },
  {
    "numero": 809,
    "piso": 8,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "FULL 2 PLAZAS",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "SI",
    "vista": "MAR"
  },
  {
    "numero": 810,
    "piso": 8,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "FULL 2 PLAZAS",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "SI",
    "vista": "MAR"
  },
  {
    "numero": 901,
    "piso": 9,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "FULL 2 PLAZAS",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "SI",
    "vista": "CERRO"
  },
  {
    "numero": 902,
    "piso": 9,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "FULL 2 PLAZAS",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "SI",
    "vista": "CERRO"
  },
  {
    "numero": 903,
    "piso": 9,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "FULL 2 PLAZAS",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "SI",
    "vista": "CERRO"
  },
  {
    "numero": 908,
    "piso": 9,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "FULL 2 PLAZAS",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "SI",
    "vista": "MAR"
  },
  {
    "numero": 909,
    "piso": 9,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "FULL 2 PLAZAS",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "SI",
    "vista": "MAR"
  },
  {
    "numero": 910,
    "piso": 9,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "FULL 2 PLAZAS",
    "cant_camas": 2,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "SI",
    "vista": "MAR"
  },
  {
    "numero": 1001,
    "piso": 10,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "QUEEN",
    "cant_camas": 1,
    "max_personas": 2,
    "condicion_esp": "PARA HIPOACUSICOS",
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "SI",
    "vista": "CERRO"
  },
  {
    "numero": 1002,
    "piso": 10,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "QUEEN",
    "cant_camas": 1,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "SI",
    "vista": "CERRO"
  },
  {
    "numero": 1003,
    "piso": 10,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "QUEEN",
    "cant_camas": 1,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "SI",
    "vista": "CERRO"
  },
  {
    "numero": 1004,
    "piso": 10,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "QUEEN",
    "cant_camas": 1,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "SI",
    "vista": "CERRO"
  },
  {
    "numero": 1005,
    "piso": 10,
    "pasillo": "ALFOMBRA",
    "bloque": "PREMIUM",
    "categoria": "SUITE PRESIDENCIAL",
    "piso_material": "MADERA",
    "cama": "KING SIZE",
    "cant_camas": 1,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": true,
    "medida_m2": 85,
    "balcon": "NO",
    "aire_ac": "SI",
    "vista": "MAR"
  },
  {
    "numero": 1006,
    "piso": 10,
    "pasillo": "ALFOMBRA",
    "bloque": "PREMIUM",
    "categoria": "SUITE PRESIDENCIAL",
    "piso_material": "MADERA",
    "cama": "KING SIZE",
    "cant_camas": 1,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": true,
    "medida_m2": 85,
    "balcon": "NO",
    "aire_ac": "SI",
    "vista": "MAR"
  },
  {
    "numero": 1007,
    "piso": 10,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "QUEEN",
    "cant_camas": 1,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "SI",
    "vista": "MAR"
  },
  {
    "numero": 1008,
    "piso": 10,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "QUEEN",
    "cant_camas": 1,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "SI",
    "vista": "MAR"
  },
  {
    "numero": 1009,
    "piso": 10,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "QUEEN",
    "cant_camas": 1,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "SI",
    "vista": "MAR"
  },
  {
    "numero": 1010,
    "piso": 10,
    "pasillo": "ALFOMBRA",
    "bloque": "GAMA MEDIA",
    "categoria": "EJECUTIVA EN SUITE",
    "piso_material": "MADERA",
    "cama": "QUEEN",
    "cant_camas": 1,
    "max_personas": 2,
    "condicion_esp": null,
    "observ": null,
    "falta_pintar": false,
    "medida_m2": 32,
    "balcon": "NO",
    "aire_ac": "SI",
    "vista": "MAR"
  }
];

const CATEGORIAS = [...new Set(ROOMS.map(r => r.categoria))].sort();
const PISOS = [...new Set(ROOMS.map(r => r.piso))].sort((a,b)=>a-b);
